name: Update GitHub Monitoring Animation

on:
  schedule:
    - cron: '0 */6 * * *' # هر ۶ ساعت
  workflow_dispatch: # امکان اجرای دستی

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Update SVG
        run: python update_stats.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add status.svg
          git commit -m "Update monitoring stats" || exit 0
          git push